// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZnalVCWN5fI5k9LNi2zp0-9SV1w7Sw5I',
    appId: '1:675705904876:web:60dc3ef4b7543de38dcfc9',
    messagingSenderId: '675705904876',
    projectId: 'flutterpushnotifications-ec185',
    authDomain: 'flutterpushnotifications-ec185.firebaseapp.com',
    storageBucket: 'flutterpushnotifications-ec185.appspot.com',
    measurementId: 'G-5GD4J6TWY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu2WnA2QT8sNl0MW_uPG7mbcVSw735h4w',
    appId: '1:675705904876:android:68fafdec39d1a6cb8dcfc9',
    messagingSenderId: '675705904876',
    projectId: 'flutterpushnotifications-ec185',
    storageBucket: 'flutterpushnotifications-ec185.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVufsAHEO5BMPQiawYPfDtGQo8iT3KMkI',
    appId: '1:675705904876:ios:0a990c10bbf5acf58dcfc9',
    messagingSenderId: '675705904876',
    projectId: 'flutterpushnotifications-ec185',
    storageBucket: 'flutterpushnotifications-ec185.appspot.com',
    iosBundleId: 'com.example.pushNotificationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVufsAHEO5BMPQiawYPfDtGQo8iT3KMkI',
    appId: '1:675705904876:ios:87dc502c782b07c18dcfc9',
    messagingSenderId: '675705904876',
    projectId: 'flutterpushnotifications-ec185',
    storageBucket: 'flutterpushnotifications-ec185.appspot.com',
    iosBundleId: 'com.example.pushNotificationApp.RunnerTests',
  );
}
